### ISSUE TITLE
panel.doInit is not a function in Grafana 5

### ISSUE THREAD

**Issue by lfdominguez** [MarcusCalidus/grafana-svg-panel#2]
Hello, I'm testing this in Grafana 5 beta and when I configure the plugin in first time, they works, but then when i update the dashboard then show the SVG, but with this error (panel.doInit is not a function)
![screenshot_20180206_162025](https://user-images.githubusercontent.com/5604131/35884760-a4a3262a-0b59-11e8-84bd-55e5b5b55b9a.png)

**Comment by MarcusCalidus** [comment]
Hi Luiz,

thank you for your input. I am a bit behind schedule with testing on Grafana 5. I will look into that issue as soon as possible.

Have a great day
Marco

**Comment by lfdominguez** [comment]
Thanks for respond, this plugin let me draw with SVG my network diagram and configure the metrics with custom grapgics, that's great !!!!!
If I add the pannel and configure it without refresh the page, then works, the problem is when refresh the page (initialize the panel).

**Comment by MarcusCalidus** [comment]
The issue is addressed in commit: https://github.com/MarcusCalidus/grafana-svg-panel/commit/9522691756a8e53d3c2d5968c1b755e2f5588bb6

Please let me know if it works for you. Thank you very much for your patience

**Comment by lfdominguez** [comment]
Great, now there are not errors!!!!!! When i finish the SVG I will show you, thanks....
