### ISSUE TITLE
SVG rendering problem

### ISSUE THREAD

**Issue by lfdominguez** [MarcusCalidus/grafana-svg-panel#3]
Hello again, I designed the SVG (with Inkscape) of the network diagram of my external networks, but when that SVG is rendered:

![screenshot_20180207_080707](https://user-images.githubusercontent.com/5604131/35917923-e5b5e556-0bdd-11e8-9f5a-3e030045e3c2.png)

There are any limitation in size of the SVG???

**Comment by lfdominguez** [comment]
the real SVG is:

![net](https://user-images.githubusercontent.com/5604131/35918063-736fdce4-0bde-11e8-809e-95af6a427a0e.png)

**Comment by MarcusCalidus** [comment]
There are no size restrictions that I know of. The plugin imports the SVG as is. It might be an issue with the svg itself. Try opening it in the browser to check if it is displayed correctly. 
You can send it to me (via e-mail) if you wish and I can check it.

**Comment by lfdominguez** [comment]
The browser open it ok (Chromium 62 on Debian testing), how can i see your mail?

**Comment by lfdominguez** [comment]
well this is the svg
[net.tar.gz](https://github.com/MarcusCalidus/grafana-svg-panel/files/1703231/net.tar.gz)

**Comment by MarcusCalidus** [comment]
I suppose it worked with the previous implementation? (pre Grafana 5)

**Comment by MarcusCalidus** [comment]
Version 5.0.0-beta1 (commit: 76c2a6e)
macOS 10.13.2
Chrome Version 64.0.3282.140 & Firefox 57.0.4 

File used as provided
![image](https://user-images.githubusercontent.com/4113366/35919763-512406b4-0c16-11e8-987b-a97c8682197a.png)

**Comment by MarcusCalidus** [comment]
you might wanna try saving the svg as "normal" from Inkscape Save dialog:
![image](https://user-images.githubusercontent.com/4113366/35919888-98764a9a-0c16-11e8-9aee-89482d8a003c.png)

**Comment by lfdominguez** [comment]
gg sems that the problem is with the new visual of grafana (i am thinking in angular), because when i optimized de svg then show more parts of the image, but is proportional to the svg size, uff, what do you think??

**Comment by lfdominguez** [comment]
Now i remove some parts of the SVG and then show me more of the image, this is a new grafana error

**Comment by MarcusCalidus** [comment]
Could you please cross check it in Firefox?

**Comment by lfdominguez** [comment]
same problem Firefox ESR (52.5)

**Comment by lfdominguez** [comment]
or my display driver....

**Comment by lfdominguez** [comment]
well i test in another PC and the problem persist, let me test with firefox 57

**Comment by lfdominguez** [comment]
Debian Testing + Firefox 57, same problem

**Comment by MarcusCalidus** [comment]
is there already some code in onInit() ?
What happens without any code at all?

**Comment by MarcusCalidus** [comment]
[net2.svg.zip](https://github.com/MarcusCalidus/grafana-svg-panel/files/1703560/net2.svg.zip)
this one is without inkscape specific code

**Comment by lfdominguez** [comment]
There is no code, only SVG

**Comment by lfdominguez** [comment]
With the file that you send to me, same problem... with your sample SVG works great

**Comment by MarcusCalidus** [comment]
you might want to try:
https://jakearchibald.github.io/svgomg/

this is the smaller result of your graphic:
[net2 (1).svg.zip](https://github.com/MarcusCalidus/grafana-svg-panel/files/1703612/net2.1.svg.zip)

**Comment by lfdominguez** [comment]
Workssss!!!!! with almost options enabled, 45% less size, so the problem is size or what??? gggg

**Comment by lfdominguez** [comment]
thanks for the link...

**Comment by MarcusCalidus** [comment]
it's strange that size could be a problem without the svg breaking. But it might be the only difference. 
Thank you for your patience. This issue may serve for future reference then :-)
